[build]
  # Build the frontend subdirectory explicitly
  command = "npm --prefix frontend ci && npm --prefix frontend run build"
  publish = "frontend/dist"

# Ensure SPA routes work on Netlify
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


